language: python
dist: focal

branches:
  only:
    - master

sudo: required
services:
  - docker

cache:
  - pip
  - directories:
    - node_modules
    - ecommerce/static/bower_components

addons:
  apt:
    packages:
      - lcov

before_install:
  - docker-compose -f ./.travis/docker-compose-travis.yml up -d

install:
  - docker exec -t ecommerce_testing bash -c "
      cd /edx/app/ecommerce/ecommerce/ &&
      pip install tox
    "
script:
  - docker exec -t -e TRAVIS=1 ecommerce_testing bash -c "
      cd /edx/app/ecommerce/ecommerce/ &&
      PATH=\$PATH:/edx/app/ecommerce/nodeenvs/ecommerce/bin:/snap/bin
      DJANGO_ENV=$DJANGO_ENV make $TARGETS
    "

matrix:
  include:
    - python: 3.8
      env:
        DJANGO_ENV=django22
        TESTNAME=quality-and-js
        TARGETS="PYTHON_ENV=py38 requirements.js check_translations_up_to_date validate_translations clean_static static quality validate_js check_keywords"
    - python: 3.8
      env:
        DJANGO_ENV=django22
        TESTNAME=test-python
        TARGETS="PYTHON_ENV=py38 requirements.js clean_static static validate_python"
      after_success:
        - pip install -U codecov
        - docker exec ecommerce_testing /edx/app/ecommerce/ecommerce/.travis/run_coverage.sh
        - codecov
