language: python
python:
    - "2.7"
sudo: false

# Cache the pip directory. "cache: pip" doesn't work due to install override. See https://github.com/travis-ci/travis-ci/issues/3239.
cache:
  - bundler
  - directories:
    - $HOME/.cache/pip
    - node_modules
    - ecommerce/static/bower_components
addons:
    apt:
        packages:
            - lcov
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
install:
    - gem install coveralls-lcov
    - pip install -r requirements/test.txt
    - pip install coveralls
    - make requirements.js
script:
    - make static -e DJANGO_SETTINGS_MODULE="ecommerce.settings.test"
    - make validate
branches:
    only:
        - master
after_success:
    - coveralls-lcov -v -n coverage/report-lcov/lcov.info > js-coverage.json
    - coveralls --merge=js-coverage.json
