name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - django-env: django32
            testname: quality-and-jobs
            targets: PYTHON_ENV=py38 requirements.js check_translations_up_to_date validate_translations clean_static static quality validate_js check_keywords
          - django-env: django32
            testname: test-python
            targets: PYTHON_ENV=py38 requirements.js clean_static static validate_python
          - django-env: django32
            testname: acceptance-python
            targets: PYTHON_ENV=py38 requirements.js clean_static static acceptance

    steps:
      - uses: actions/checkout@v2
      - name: Start container
        run: |
          docker-compose -f ./.ci/docker-compose-ci.yml up -d
      - name: Install dependencies
        run: |
          docker exec -t ecommerce_testing bash -c "
            cd /edx/app/ecommerce/ecommerce/ &&
            python3 -m pip install tox
          "
      - name: Run tests
        run: |
          docker exec -t -e CI=1 ecommerce_testing bash -c "
            cd /edx/app/ecommerce/ecommerce/ &&
            PATH=\$PATH:/edx/app/ecommerce/nodeenvs/ecommerce/bin:/snap/bin
            DJANGO_ENV=${{ matrix.django-env }} make ${{ matrix.targets }}
          "
      - name: Run coverage
        if: matrix.testname == 'test-python'
        run: |
          docker exec ecommerce_testing /edx/app/ecommerce/ecommerce/.ci/run_coverage.sh
      - name: Setup Python
        if: matrix.testname == 'test-python'
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: x64
      - name: Report coverage
        if: matrix.testname == 'test-python'
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          fail_ci_if_error: false

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: x64
      - name: Install Dependencies
        run: pip install -r requirements/docs.txt -r requirements/tox.txt
      - name: Build the docs
        run: make docs
